### ISSUE TITLE
Storybook is broken

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#546]
Storybook seems to be currently broken. It seems like there's multiple PR's that has caused the regression.

We have to move `.storybook` folder into the package folder (https://github.com/jsdrupal/drupal-admin-ui/pull/516) and we have to make the storybook config support TypeScript (https://github.com/jsdrupal/drupal-admin-ui/pull/537)

**Comment by martinfrances107** [comment]
I can confirm this bug.... I will take a look at this tomorrow

I think .storybook does needs to be copied from the root directory 
down into 

packages/admin-ui

After that 

yarn workspace admin-ui storybook

does not completely work.. but this time the server starts ..  it needs further work

here is the next stacktrace 

`    ReferenceError: exports is not defined
    at Module../src/components/02_atoms/FileUpload/FileUpload.js (http://localhost:9001/static/iframe.bundle.js:91027:23)
    at __webpack_require__ (http://localhost:9001/static/iframe.bundle.js:725:30)
    at fn (http://localhost:9001/static/iframe.bundle.js:102:20)
    at Module.<anonymous> (http://localhost:9001/static/iframe.bundle.js:91729:19)
    at Module../src/components/02_atoms/FileUpload/FileUpload.stories.js (http://localhost:9001/static/iframe.bundle.js:91765:30)
    at __webpack_require__ (http://localhost:9001/static/iframe.bundle.js:725:30)
    at fn (http://localhost:9001/static/iframe.bundle.js:102:20)
    at webpackContext (http://localhost:9001/static/iframe.bundle.js:90994:9)
    at http://localhost:9001/static/iframe.bundle.js:90967:12
    at Array.forEach (<anonymous>)`

**Comment by martinfrances107** [comment]
I am just posting an initial version....

Here is a comment which points out where the error is and what I don't understand

"exports is coming from commonJS"

https://stackoverflow.com/questions/43042889/typescript-referenceerror-exports-is-not-defined

**Comment by martinfrances107** [comment]
This is the first unmet dependency we have 

> warning "workspace-aggregator-1b2a520b-178a-4eb0-af00-57875c464673 > admin-ui > @storybook/react@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".

So I am picking out quotes from a relevant open storybook issue.

https://github.com/storybooks/storybook/issues/4764

>This is a problem, when installing babel-loader, it requires webpack but these two dependencies are already the required dependencies of react-scripts for CRA2 which loads them.

> I don't believe it is good to make users install babel-loader or @babel-core when CRA is there, it will conflict and devs will have a trouble upgrading in the future.

> Is there a better way to support this? For example, once #4587 is supported, can we infer these packages like how CRA2 does it?

I think the solution of this will have to wait.

**Comment by martinfrances107** [comment]
I am going to link a second isolated PR to this main issue.

All I said above can be wiped away from consideration by resolving our unmet dependencies.

This pull request is the result of running

yarn add storybook --dev 

in ./packages/admin-ui

It does not change the storybook errors. but it does put back our little project on firm ground.

**Comment by martinfrances107** [comment]
What comes next is something I need to bring up at the next  Monday meeting.

This is solve the problem I described above...  "we need a common configuration between storybook and production environments" is best described in short form by -- 

We need storybook to pull in our existing tsconfig.json file.

This is simple ..The instructions are here https://storybook.js.org/configurations/typescript-config/

and I nominate myself for possibly doing it -- there is just a question of code quality. I have seen justafish exercise the professionally minded  preflight check before ingesting a new package/module.

The official story book instruction above talk about pulling in 
https://www.npmjs.com/package/react-docgen-typescript-webpack-plugin

But this is where we **fail** the preflight checks. If one visits the home page of the "react-docgen-typescript-webpack-plugin" this is what you see...

> This plugin is mostly a hack job at the moment. It is a work in progress so it is most likely not suitable for production. Pull requests are most welcome.

This is the uncomfortable conclusion.. there is no good way of including storybook and typescript.

We cannot have both... Anyway this need talking through on Monday. 

a)  Maybe there is some middle ground where we revert some js files to jsx .. but even I will not argue strongly for that.

b) Maybe we can create a .babelrc that storybook will pick up and allow JSX elements to be parsed in js files. ( the current unsolved problem )

**Comment by mattgrill** [comment]
@martinfrances107 This custom webpack module, does this mean we need to eject from CRA?

**Comment by martinfrances107** [comment]
> does this mean we need to eject from CRA?

No I don't think so.. if I understand things correctly. An overview of the instructions listed by storybook in the URL above : -

A) Add a few modules using "yarn add XYX --dev"

B) Make changes to storybook's webpack config in isolation from the main project by altering files within the .storybook directory.
