### ISSUE TITLE
test_node fails frequently on CircleCI

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#594]
![nodeeditformrestoring_failed_dec-21-2018-091232-gmt 0000- coordinated-universal 1](https://user-images.githubusercontent.com/345613/50335058-0eed0a80-0502-11e9-9049-d99c3929ae78.png)

```
Timed out while waiting for element <[data-nightwatch="Edit Super easy vegetarian pasta bake"]> to be present for 5000 milliseconds. - expected [0;32m"visible"[0m but got: [0;31m"not found"[0m
    at Object.nodeEditFormRestoring (/root/drupal-admin-ui/packages/admin-ui/src/tests/Nightwatch/Tests/NodeEdit.js:36:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dawehner** [comment]
There is a second random failure:

```
Timed out while waiting for element <[data-nightwatch="content-type-select"]> to be present for 5000 milliseconds. - expected [0;32m"visible"[0m but got: [0;31m"not found"[0m
```

**Comment by dawehner** [comment]
Example of it failing:


https://circleci.com/gh/jsdrupal/drupal-admin-ui/7617?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I've identified the potential error on the content page, but I wasn't yet successful for the node edit form.
https://github.com/jsdrupal/drupal-admin-ui/pull/603/files contains these fixes plus some additional logging.
